### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by virtadpt** [w84death/smolOS#5]
```
Super Quick Quide

Just put main.py into the board (that has latest MicroPython firmware) and restart.
```
Don't you mean `smolos.py`?

**Comment by w84death** [comment]
Thanks for pointing that out. I need to write it better.

smolos.py is now the OS file (in latest commits for compatibility).

main.py is the file that will be executed automatycally at boot by the device. So it will "boot" into the smolOS at every boot.

If you copy smolos.py and in your main.py file include it and run it will be the same effect.
